//TODO: Have single source of color by importing from variables.scs
const COLOR_PRIMARY = "#00205C"
const COLOR_WHITE = "#FFFFFF"
const COLOR_SEC_BLUE = "#009ADE"
const COLOR_SEC_ORANGE = "#F26829"
const COLOR_SEC_YELLOW = "#F4A81D"
const COLOR_SEC_MAGENTA = "#A6228C"
const COLOR_SEC_PURPLE = "#5B2C86"
const COLOR_SEC_GREEN = "#80BC00"
const COLOR_RED = "#EF3842"
    
export default {
  COLOR_PRIMARY: COLOR_PRIMARY,
  COLOR_WHITE: COLOR_WHITE,
  COLOR_SEC_BLUE: COLOR_SEC_BLUE,
  COLOR_SEC_ORANGE: COLOR_SEC_ORANGE,
  COLOR_SEC_YELLOW: COLOR_SEC_YELLOW,
  COLOR_SEC_MAGENTA: COLOR_SEC_MAGENTA,
  COLOR_SEC_PURPLE: COLOR_SEC_PURPLE,
  COLOR_SEC_GREEN: COLOR_SEC_GREEN,
  COLOR_RED: COLOR_RED,
}